apiVersion: lb.faros.dev/v1beta1
kind: ClusterLoadBalancer
metadata:
  name: example-clusterloadbalancer
spec:
  vip_addr: '192.168.8.60'
  router_id: '100'
  vip_pass: 'SecretP4SS'
  node_selector:
    node-role.kubernetes.io/master: ""
