apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hosted-loadbalancer
  namespace: openshift-hosted-loadbalancer
  labels:
    k8s-app: hosted-loadbalancer
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: hosted-loadbalancer
  template:
    metadata:
      labels:
        k8s-app: hosted-loadbalancer
    spec:
      containers:
      - name: keepalived
        imagePullPolicy: always
        image: quay.io/faros/hosted-loadbalancer-keepalived:dev
        serviceAccountName: hosted-loadbalancer
        securityContext:
          privileged: true
          runAsUser: 0
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: hosted-loadbalancer
      priorityClassName: "system-cluster-critical"
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
