apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterloadbalancers.lb.faros.dev
spec:
  version: v1beta1
  group: lb.faros.dev
  names:
    kind: ClusterLoadBalancer
    listKind: ClusterLoadBalancerList
    plural: clusterloadbalancers
    singular: clusterloadbalancer
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1beta1
    served: true
    storage: false
