apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hosted-loadbalancer
  namespace: openshift-hosted-loadbalancer
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hosted-loadbalancer
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hosted-loadbalancer
  namespace: openshift-hosted-loadbalancer
subjects:
- kind: ServiceAccount
  name: hosted-loadbalancer
roleRef:
  kind: Role
  name: hosted-loadbalancer
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hosted-loadbalancer
subjects:
- kind: ServiceAccount
  name: hosted-loadbalancer
  namespace: openshift-hosted-loadbalancer
roleRef:
  kind: ClusterRole
  name: hosted-loadbalancer
  apiGroup: rbac.authorization.k8s.io
